---
author: "Thierry Onkelinx"
date: "`r paste('Versie:', format(Sys.time(), '%e/%m/%Y %T %Z'))`"
header-includes:
   - \usepackage[dutch]{babel}
output: pdf_document
params:
  studyarea: 1
  crs: "+init=epsg:31370"
  cellsize: 100
  detail_width: 6
  detail_height: 8
---

```{r setup, include=FALSE}
library(knitr)
opts_chunk$set(
  cache = TRUE,
  autodep = TRUE,
  message = FALSE,
  echo = FALSE
)
library(rgdal)
library(rgeos)
library(osmar)
library(dplyr)
library(ggplot2)
```

```{r load_data}
studyarea <- readOGR("studyarea.geojson", verbose = FALSE) %>%
  subset(id == params$studyarea)
route <- readOGR("route.geojson", verbose = FALSE) %>%
  subset(studyarea == params$studyarea)
```

---
title: "`r paste('Veldformulier', studyarea$name)`"
---

+-----------------+-------------------------------------------------------+
| Datum:          |                                                       |
+-----------------+-------------------------------------------------------+
|                 |                                                       |
+-----------------+-------------------------------------------------------+
| Onderzoeker 1 : |                                                       |
+-----------------+-------------------------------------------------------+
|                 |                                                       |
+-----------------+-------------------------------------------------------+
| Onderzoeker 2 : |                                                       |
+-----------------+-------------------------------------------------------+
|                 |                                                       |
+-----------------+-------------------------------------------------------+
| Onderzoeker 3 : |                                                       |
+-----------------+-------------------------------------------------------+
|                 |                                                       |
+-----------------+-------------------------------------------------------+
| Onderzoeker 4 : |                                                       |
+-----------------+-------------------------------------------------------+
|                 |                                                       |
+-----------------+-------------------------------------------------------+
| Onderzoeker 5 : |                                                       |
+-----------------+-------------------------------------------------------+
|                 |                                                       |
+-----------------+-------------------------------------------------------+


```{r project}
studyarea_proj <- spTransform(studyarea, CRS(params$crs))
studyarea_buffer <- studyarea_proj %>%
  gBuffer(width = 5 * params$cellsize) %>%
  spTransform(CRS("+proj=longlat"))
if (length(route) > 0) {
  route_proj <- spTransform(route, CRS(params$crs))
}
```

```{r find_optimal_angle}
raw_coordinates <- lapply(
  studyarea_proj@polygons,
  function(x){
    x@Polygons %>%
      lapply(coordinates) %>%
      do.call(what = "rbind")
  }
) %>%
  do.call(what = "rbind")
center <- apply(raw_coordinates, 2, range) %>%
  colMeans()
raw_coordinates <- raw_coordinates - matrix(center, byrow = TRUE, ncol = 2, nrow = nrow(raw_coordinates))
bb_area <- function(raw_coordinates, angle){
  raw_coordinates %*%
    matrix(c(cos(angle), sin(angle), -sin(angle), cos(angle)), ncol = 2) %>%
    apply(2, range) %>%
    apply(2, diff) %>%
    prod()
}
angle <- optimize(bb_area, interval = c(0, -pi / 2), raw_coordinates = raw_coordinates)$minimum
```

```{r rotate_studyarea}
studyarea_local <- studyarea_proj
studyarea_local@proj4string <- CRS("")
studyarea_local@polygons <- lapply(
  studyarea_local@polygons,
  function(x){
    x@Polygons <- lapply(
      x@Polygons,
      function(y){
        y@coords <- -matrix(center, byrow = TRUE, ncol = 2, nrow = nrow(y@coords)) %>%
          "+"(y@coords) %>%
          "%*%"(matrix(c(cos(angle), sin(angle), -sin(angle), cos(angle)), ncol = 2))
        return(y)
      }
    )
    return(x)
  }
)
studyarea_df <- fortify(studyarea_local)
```

```{r rotate_route}
if (length(route) > 0) {
  route_local <- route_proj
  route_local@proj4string <- CRS("")
  route_local@lines <- lapply(
    route_local@lines,
    function(x){
      x@Lines <- lapply(
        x@Lines,
        function(y){
          y@coords <- -matrix(center, byrow = TRUE, ncol = 2, nrow = nrow(y@coords)) %>%
            "+"(y@coords) %>%
            "%*%"(matrix(c(cos(angle), sin(angle), -sin(angle), cos(angle)), ncol = 2))
          return(y)
        }
      )
      return(x)
    }
  )
}
```

```{r local_grid}
grid_df <- expand.grid(
  long = seq(
    min(studyarea_df$long),
    max(studyarea_df$long),
    by = params$cellsize
  ),
  lat = seq(
    min(studyarea_df$lat),
    max(studyarea_df$lat),
    by = params$cellsize
  )
)
grid_local <- lapply(
  seq_along(grid_df$long), 
  function(i){
    cbind(
      grid_df$long[i] + params$cellsize * c(0, 1, 1, 0, 0),
      grid_df$lat[i] + params$cellsize * c(0, 0, 1, 1, 0)
    ) %>%
      Polygon() %>%
      list() %>%
      Polygons(ID = i)
  }
) %>%
  SpatialPolygons()
grid_local$surveyed <- rep(0, length(grid_local))
if (length(route) > 0) {
  surveyed <- gBuffer(route_local, width = 20) %>%
    gIntersection(grid_local, byid = TRUE) %>%
    gArea(byid = TRUE) %>%
    "/"(params$cellsize ^ 2)
  grid_local$surveyed[
    gsub("buffer ", "", names(surveyed)) %>%
      as.integer()
  ] <- surveyed
}
grid_df <- fortify(grid_local)
grid_df$surveyed <- grid_local$surveyed[as.integer(grid_df$id)]
  
overlap <- gRelate(studyarea_local, grid_local, byid = TRUE) %>%
  as.vector() %>%
  grepl(pattern = "^2")
grid_local <- grid_local[overlap, ]
grid_df <- grid_df %>%
  filter(id %in% which(overlap))
```

```{r import_osm}
osm <- as_osmar_bbox(studyarea_buffer) %>%
  get_osm()
```

```{r osm_local_coordinates}
osm_local <- SpatialPointsDataFrame(
  coords = osm$nodes$attrs %>%
    select(long = lon, lat), 
  data = osm$nodes$attrs %>%
    select(ref = id), 
  proj4string = studyarea@proj4string
) %>%
  spTransform(CRS(params$crs)) %>%
  as.data.frame() %>%
  mutate(
    x = long - center[1], 
    y = lat - center[2],
    long = cos(angle) * x + sin(angle) * y,
    lat = -sin(angle) * x + cos(angle) * y
  ) %>%
  select(-x, -y)
```

```{r osm_layers}
road <- osm$ways$tags %>%
  filter(
    k == "highway"
  ) %>%
  mutate(
    class = ifelse(
      v %in% c("cycleway", "footway", "path", "pedestrian", "steps", "track"),
      "path",
      "road"
    ) %>%
      factor(levels = c("road", "path"))
  ) %>%
  inner_join(osm$ways$refs, by = "id") %>%
  inner_join(osm_local, by = "ref")
waterway <- osm$ways$tags %>%
  filter(k == "waterway") %>%
  inner_join(osm$ways$refs, by = "id") %>%
  inner_join(osm_local, by = "ref")
forest <- osm$ways$tags %>%
  filter(k == "landuse", v == "forest") %>%
  inner_join(osm$ways$refs, by = "id") %>%
  inner_join(osm_local, by = "ref") %>%
  select(id, long, lat)
forest <- osm$relations$tags %>%
  filter(k == "landuse", v == "forest") %>%
  inner_join(osm$relations$refs, by = "id") %>%
  inner_join(osm$ways$refs, by = c("ref" = "id")) %>%
  inner_join(osm_local, by = c("ref.y" = "ref")) %>%
  select(id, long, lat) %>%
  bind_rows(forest)
water <- osm$ways$tags %>%
  filter(k == "natural", v == "water") %>%
  inner_join(osm$ways$refs, by = "id") %>%
  inner_join(osm_local, by = "ref") %>%
  select(id, long, lat)
water <- osm$relations$tags %>%
  filter(k == "natural", v == "water") %>%
  inner_join(osm$relations$refs, by = "id") %>%
  inner_join(osm$ways$refs, by = c("ref" = "id")) %>%
  inner_join(osm_local, by = c("ref.y" = "ref")) %>%
  select(id, long, lat) %>%
  bind_rows(water)
grass <- osm$ways$tags %>%
  filter((k == "natural" & v == "grasland") | (k == "landuse" & v %in% c("grass", "meadow"))) %>%
  inner_join(osm$ways$refs, by = "id") %>%
  inner_join(osm_local, by = "ref") %>%
  select(id, long, lat)
grass <- osm$relations$tags %>%
  filter((k == "natural" & v == "grasland") | (k == "landuse" & v %in% c("grass", "meadow"))) %>%
  inner_join(osm$relations$refs, by = "id") %>%
  inner_join(osm$ways$refs, by = c("ref" = "id")) %>%
  inner_join(osm_local, by = c("ref.y" = "ref")) %>%
  select(id, long, lat) %>%
  bind_rows(grass)
building <- osm$ways$tags %>%
  filter(k == "building") %>%
  inner_join(osm$ways$refs, by = "id") %>%
  inner_join(osm_local, by = "ref") %>%
  select(id, long, lat)
```

```{r overview_map, cache = FALSE, results="asis"}
rmd <- knit_expand(
  "_fieldnotes_map.Rmd", 
  id = "overzicht",
  xmin = min(grid_df$long), 
  xmax = max(grid_df$long), 
  ymin = min(grid_df$lat), 
  ymax = max(grid_df$lat),
  fill = "",
  fig.cap = "Overzicht",
  fig.width = opts_current$get("fig.width"),
  fig.height = opts_current$get("fig.height")
)
knit_child(text = rmd, quiet = TRUE) %>%
  cat()
```

```{r surveyed_map, cache = FALSE, results="asis"}
rmd <- knit_expand(
  "_fieldnotes_map.Rmd", 
  id = "route",
  xmin = min(grid_df$long), 
  xmax = max(grid_df$long), 
  ymin = min(grid_df$lat), 
  ymax = max(grid_df$lat),
  fill = "surveyed",
  fig.cap = "Huidige inventarisatieinspanning per rastercel.",
  fig.width = opts_current$get("fig.width"),
  fig.height = opts_current$get("fig.height")
)
knit_child(text = rmd, quiet = TRUE) %>%
  cat()
```

```{r detailed_maps, cache = FALSE, results = "asis", fig.width=10, fig.height=12}
rmd <- base <- grid_df %>%
  summarise(
    xmin = min(long),
    ymin = min(lat),
    xmax = max(long),
    ymax = max(lat),
    nx = ceiling((xmax - xmin) / params$cellsize / params$detail_width),
    ny = ceiling((ymax - ymin) / params$cellsize / params$detail_height)
  )
rmd <- expand.grid(
  idx = seq_len(base$nx),
  idy = seq_len(base$ny)
) %>%
  mutate(
    xmin = seq(
      base$xmin,
      base$xmax - params$cellsize * params$detail_width,
      length.out = base$nx
    )[idx],
    ymin = seq(
      base$ymin,
      base$ymax - params$cellsize * params$detail_height,
      length.out = base$ny
    )[idy],
    xmax = xmin + params$cellsize * params$detail_width,
    ymax = ymin + params$cellsize * params$detail_height,
    id = paste(idx, idy, sep = "-"),
    caption = paste("Detailkaart", id)
  ) %>%
  apply(
    1, 
    function(x){
      knit_expand(
        "_fieldnotes_map.Rmd", 
        id = x["id"],
        xmin = x["xmin"], 
        xmax = x["xmax"], 
        ymin = x["ymin"], 
        ymax = x["ymax"], 
        fill = "",
        fig.cap = x["caption"],
        fig.width = opts_current$get("fig.width"),
        fig.height = opts_current$get("fig.height")
      )
    }
  ) %>%
  paste(collapse = "\n")
knit_child(text = rmd, quiet = TRUE) %>%
  cat()
```

